### ISSUE TITLE
Create parent class PlayableMediaAsset for VideoAsset and AudioAsset to inherit from

### ISSUE THREAD

**Issue by kalegd** [kalegd/DigitalBacon#18]
👋 Hello new potential contributors (current contributors welcome as well),

[AudioAsset.js](https://github.com/kalegd/DigitalBacon/blob/ae8b6c55faaaa586c89b6fbbb385565010f06215/scripts/core/assets/AudioAsset.js) and [VideoAsset.js](https://github.com/kalegd/DigitalBacon/blob/ae8b6c55faaaa586c89b6fbbb385565010f06215/scripts/core/assets/VideoAsset.js) have a lot of common parameters and functionality. It would be great to create a PlayableMediaAsset class that takes all those common variables + functions and have AudioAsset + VideoAsset inherit from it

Quick call out that VideoAsset has a subscription that doesn't belong in `_addPartySubscriptions()`. Shame on me for placing it there...
https://github.com/kalegd/DigitalBacon/blob/ae8b6c55faaaa586c89b6fbbb385565010f06215/scripts/core/assets/VideoAsset.js#L196-L201

So `_addPartySubscriptions()` can be part of PlayableMediaAsset, but that subscription to `SESSION_STARTED` should be in a separate function only called in the constructor of VideoAsset

Also instead of referencing `this._audio` and `this._video` like we currently do, I think `_media` would be nice for the parent class. Might also need some functions that get overridden to get the current progress of the media or if they're currently playing since it happens differently for both

Additionally we'll want to create a PlayableMediaAssetHelper that is a parent to both [AudioAssetHelper](https://github.com/kalegd/DigitalBacon/blob/ae8b6c55faaaa586c89b6fbbb385565010f06215/scripts/core/helpers/editor/AudioAssetHelper.js) and [VideoAssetHelper](https://github.com/kalegd/DigitalBacon/blob/ae8b6c55faaaa586c89b6fbbb385565010f06215/scripts/core/helpers/editor/VideoAssetHelper.js)

Please comment on this issue first if you'd like to work on it. Hopefully that's enough information to get anyone through this

**Comment by VTPrince** [comment]
Hey @kalegd, i'd like to work on this issue ,i tried to run this locally by forking the repo and running "npm start" but the homepage displays this error message "Error Loading Default Environment". Could you explain to me why this might be happening?

**Comment by kalegd** [comment]
Hi @VTPrince, thanks for reaching out about working on this issue. Sorry to hear about the project not running for you... That's frustrating. I'm assuming you already ran `npm install` to download the dependencies. Do you mind doing me a favor and providing me the type of computer you're using, the browser, and the error message/stack trace given in the developer console?

I was not able to reproduce the issue on my computer so I'm curious on what the issue might be

**Comment by ShaunFrost** [comment]
Hello @kalegd, I came across what you are building and having recently developed interest in three js, I would like to contribute to the project starting here.

**Comment by kalegd** [comment]
Hi @ShaunFrost, appreciate your interest in contributing. I've gone ahead and assigned you to this task. Please feel free reach out if you have any questions

**Comment by 0x11110** [comment]
Has this issue been resolved?

**Comment by kalegd** [comment]
@0x11110 This issue is currently being worked on by @ShaunFrost. If you are interested in contributing, #27 is currently available

**Comment by kalegd** [comment]
#38 has been merged so resolving this issue
