### ISSUE TITLE
[Jest Tests] Add tests for PointerInteractable.js

### ISSUE THREAD

**Issue by kalegd** [kalegd/DigitalBacon#32]
👋 Hello new potential contributors (current contributors welcome as well),

[PointerInteractable](https://github.com/kalegd/DigitalBacon/blob/dev/scripts/core/interactables/PointerInteractable.js) is very integral to DigitalBacon, and is high on priority list of what needs unit testing. If you're unfamiliar with testing using jest, please see the [existing tests for PubSub](https://github.com/kalegd/DigitalBacon/blob/dev/tests/scripts/core/handlers/PubSub.test.js) as an example and checkout the [Jest documentation](https://jestjs.io/docs/getting-started)

I'd like the following test cases made (feel free to tackle just a portion or all of them) in a file called `/tests/scripts/core/interactables/PointerInteractable.test.js`

* action triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function (see [documentation](https://jestjs.io/docs/mock-functions) for `jest.fn()` if you are unfamiliar)
  * Verify callback function triggers when `triggerActions(...)` is called with the provided `owner` and `closestPoint` parameters

* multiple actions triggered
  * Create a PointerInteractable and call `addAction(...)` twice with mocked callback functions
  * Verify both callback functions trigger when `triggerActions(...)` is called with the provided `owner` and `closestPoint` parameters

* action for tool triggered
  * Mock `ToolHandler.getType()` to provide some tool value
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function and the aforementioned tool value
  * Verify callback function triggers when `triggerActions(...)` is called with the provided `owner` and `closestPoint` parameters

* action for different tool not triggered
  * Mock `ToolHandler.getType()` to provide some tool value
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function and a different tool value
  * Verify callback function is not called after `triggerActions(...)` is called

* action with maxDistance triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function and a maxDistance value
  * Verify callback function triggers when `triggerActions(..., {value less than maxDistance})` is called with the provided `owner` and `closestPoint` parameters

* action with maxDistance not triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function and a maxDistanceValue
  * Verify callback function is not called after `triggerActions(..., {value greater than maxDistance})` is called

* removed action not triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function followed by `removeAction(...)` with the id of the returned action
  * Verify callback function is not called after `triggerActions(...)` is called

* action triggered by state change
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function
  * Verify callback function triggers when `addSelectedBy(...)` and `addHoveredBy(...)` are called in that order with the provided `owner` and `closestPoint` parameters

* action not triggered by state changes from different owners
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function
  * Verify callback function is not called after `addSelectedBy(...)` and `addHoveredBy(...)` are called

* draggable action triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function as the second parameter
  * Verify callback function triggers when `triggerDraggableActions(...)` is called with the provided `owner` and `closestPoint` parameters

* draggable action with maxDistance triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function as the second parameter and a maxDistance value
  * Verify callback function triggers when `triggerDraggableActions(..., {value less than maxDistance})` is called with the provided `owner` and `closestPoint` parameters

* draggable action with maxDistance not triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function as the second parameter and a maxDistance value
  * Verify callback function not called after `triggerDraggableActions(..., {value greater than maxDistance})` is called

* draggable action with maxDistance going out of range still triggered
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function as the second parameter and a maxDistance value
  * Verify callback function triggers twice when `triggerDraggableActions(..., {value less than maxDistance})` is called followed by `triggerDraggableActions(..., {value greater than maxDistance})`

* draggable action triggered by state change
  * Create a PointerInteractable and call `addAction(...)` with a mocked callback function as the second parameter
  * Verify callback function triggers after `addSelectedBy(...)` is called in that order with the provided `owner` and `closestPoint` parameters

**Comment by justjo3l** [comment]
Hi @kalegd, I have read through this issue and would like to contribute this feature!

**Comment by kalegd** [comment]
Hi @justjo3l, thanks for reaching out about this issue! I've gone ahead and assigned you this issue :)

**Comment by justjo3l** [comment]
Thanks! I have just sent a PR (#36) through, please take a look and advise!
