### ISSUE TITLE
Add eslint to npm project

### ISSUE THREAD

**Issue by kalegd** [kalegd/DigitalBacon#7]
👋 Hello new potential contributors,

Something I should have done from the beginning of this project is use a linter to keep a consistent coding style. Unfortunately I did not...
<img src="https://i.imgflip.com/28jcie.jpg" width="128">

Would appreciate it if someone could add eslint with the following rules to start
* [warning] 80 character limit on lines
* [error] indents should be 4 spaces (if it's possible to not apply this to comments that would be great!)
* [error] always use semicolons at the end of lines
* [error] check arrow functions that only have a single line return and force them to not be in curly braces
* [error] check for dead references... too many imports/variables that aren't used anymore in files

Here's a quick getting started guide for eslint if you're unfamiliar, I'd prefer a json structure for the rules for this project
https://eslint.org/docs/latest/use/getting-started

To start I just want a pull request with the linter working via `npm run lint`, fixing the errors + warns will be tracked in a separate issue https://github.com/kalegd/DigitalBacon/issues/9

Please reply to this issue first if you'd like to work on it

**Comment by laurittab** [comment]
Hi kalegd,

I use eslint a lot for my backend work. It's be great if I could work on this, my first contribution :-)

Lauritta

**Comment by kalegd** [comment]
Hi Laurittab, thanks! I've gone ahead and assigned this issue to you. Please let me know if you have any questions

**Comment by laurittab** [comment]
Thanks for that. I'll make a start tomorrow.
